fragment PageParts on Page {
  __typename
  title
  heroTitle
  heroSubtitle
  ctaLabel
  ctaLink
  highlights {
    __typename
    title
    description
  }
}

fragment SiteSettingsParts on SiteSettings {
  __typename
  companyName
  tagline
  nav {
    __typename
    label
    href
  }
}
