//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  /** Internal type. DO NOT USE DIRECTLY. */
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
/** Internal type. DO NOT USE DIRECTLY. */
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  siteSettings: SiteSettings;
  siteSettingsConnection: SiteSettingsConnection;
  featuredProperty: FeaturedProperty;
  featuredPropertyConnection: FeaturedPropertyConnection;
  ongoingProject: OngoingProject;
  ongoingProjectConnection: OngoingProjectConnection;
  completedProject: CompletedProject;
  completedProjectConnection: CompletedProjectConnection;
  stats: Stats;
  statsConnection: StatsConnection;
  testimonial: Testimonial;
  testimonialConnection: TestimonialConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySiteSettingsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySiteSettingsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SiteSettingsFilter>;
};


export type QueryFeaturedPropertyArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryFeaturedPropertyConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FeaturedPropertyFilter>;
};


export type QueryOngoingProjectArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryOngoingProjectConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<OngoingProjectFilter>;
};


export type QueryCompletedProjectArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryCompletedProjectConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<CompletedProjectFilter>;
};


export type QueryStatsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryStatsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<StatsFilter>;
};


export type QueryTestimonialArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTestimonialConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TestimonialFilter>;
};

export type DocumentFilter = {
  siteSettings?: InputMaybe<SiteSettingsFilter>;
  featuredProperty?: InputMaybe<FeaturedPropertyFilter>;
  ongoingProject?: InputMaybe<OngoingProjectFilter>;
  completedProject?: InputMaybe<CompletedProjectFilter>;
  stats?: InputMaybe<StatsFilter>;
  testimonial?: InputMaybe<TestimonialFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = SiteSettings | FeaturedProperty | OngoingProject | CompletedProject | Stats | Testimonial | Folder;

export type SiteSettingsComingSoon = {
  __typename?: 'SiteSettingsComingSoon';
  headline: Scalars['String']['output'];
  message: Scalars['String']['output'];
  showContact?: Maybe<Scalars['Boolean']['output']>;
};

export type SiteSettings = Node & Document & {
  __typename?: 'SiteSettings';
  published?: Maybe<Scalars['Boolean']['output']>;
  comingSoon?: Maybe<SiteSettingsComingSoon>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type SiteSettingsComingSoonFilter = {
  headline?: InputMaybe<StringFilter>;
  message?: InputMaybe<StringFilter>;
  showContact?: InputMaybe<BooleanFilter>;
};

export type SiteSettingsFilter = {
  published?: InputMaybe<BooleanFilter>;
  comingSoon?: InputMaybe<SiteSettingsComingSoonFilter>;
};

export type SiteSettingsConnectionEdges = {
  __typename?: 'SiteSettingsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<SiteSettings>;
};

export type SiteSettingsConnection = Connection & {
  __typename?: 'SiteSettingsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SiteSettingsConnectionEdges>>>;
};

export type FeaturedPropertyGallery = {
  __typename?: 'FeaturedPropertyGallery';
  image: Scalars['String']['output'];
  alt: Scalars['String']['output'];
};

export type FeaturedProperty = Node & Document & {
  __typename?: 'FeaturedProperty';
  title: Scalars['String']['output'];
  tag?: Maybe<Scalars['String']['output']>;
  description: Scalars['String']['output'];
  price: Scalars['String']['output'];
  areaSqft: Scalars['Float']['output'];
  propertyType: Scalars['String']['output'];
  bedrooms?: Maybe<Scalars['Float']['output']>;
  bathrooms?: Maybe<Scalars['Float']['output']>;
  locality: Scalars['String']['output'];
  possession?: Maybe<Scalars['String']['output']>;
  facing?: Maybe<Scalars['String']['output']>;
  gallery: Array<FeaturedPropertyGallery>;
  featured?: Maybe<Scalars['Boolean']['output']>;
  order?: Maybe<Scalars['Float']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type FeaturedPropertyGalleryFilter = {
  image?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type FeaturedPropertyFilter = {
  title?: InputMaybe<StringFilter>;
  tag?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  price?: InputMaybe<StringFilter>;
  areaSqft?: InputMaybe<NumberFilter>;
  propertyType?: InputMaybe<StringFilter>;
  bedrooms?: InputMaybe<NumberFilter>;
  bathrooms?: InputMaybe<NumberFilter>;
  locality?: InputMaybe<StringFilter>;
  possession?: InputMaybe<StringFilter>;
  facing?: InputMaybe<StringFilter>;
  gallery?: InputMaybe<FeaturedPropertyGalleryFilter>;
  featured?: InputMaybe<BooleanFilter>;
  order?: InputMaybe<NumberFilter>;
};

export type FeaturedPropertyConnectionEdges = {
  __typename?: 'FeaturedPropertyConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<FeaturedProperty>;
};

export type FeaturedPropertyConnection = Connection & {
  __typename?: 'FeaturedPropertyConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<FeaturedPropertyConnectionEdges>>>;
};

export type OngoingProjectGallery = {
  __typename?: 'OngoingProjectGallery';
  image: Scalars['String']['output'];
  alt: Scalars['String']['output'];
};

export type OngoingProject = Node & Document & {
  __typename?: 'OngoingProject';
  title: Scalars['String']['output'];
  description: Scalars['String']['output'];
  location: Scalars['String']['output'];
  projectType: Scalars['String']['output'];
  percentComplete?: Maybe<Scalars['Float']['output']>;
  expectedCompletion?: Maybe<Scalars['String']['output']>;
  gallery: Array<OngoingProjectGallery>;
  videoUrl?: Maybe<Scalars['String']['output']>;
  order?: Maybe<Scalars['Float']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type OngoingProjectGalleryFilter = {
  image?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type OngoingProjectFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  location?: InputMaybe<StringFilter>;
  projectType?: InputMaybe<StringFilter>;
  percentComplete?: InputMaybe<NumberFilter>;
  expectedCompletion?: InputMaybe<StringFilter>;
  gallery?: InputMaybe<OngoingProjectGalleryFilter>;
  videoUrl?: InputMaybe<StringFilter>;
  order?: InputMaybe<NumberFilter>;
};

export type OngoingProjectConnectionEdges = {
  __typename?: 'OngoingProjectConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<OngoingProject>;
};

export type OngoingProjectConnection = Connection & {
  __typename?: 'OngoingProjectConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<OngoingProjectConnectionEdges>>>;
};

export type CompletedProjectGallery = {
  __typename?: 'CompletedProjectGallery';
  image: Scalars['String']['output'];
  alt: Scalars['String']['output'];
};

export type CompletedProject = Node & Document & {
  __typename?: 'CompletedProject';
  title: Scalars['String']['output'];
  description: Scalars['String']['output'];
  location: Scalars['String']['output'];
  projectType: Scalars['String']['output'];
  completedYear: Scalars['Float']['output'];
  durationMonths?: Maybe<Scalars['Float']['output']>;
  gallery: Array<CompletedProjectGallery>;
  videoUrl?: Maybe<Scalars['String']['output']>;
  order?: Maybe<Scalars['Float']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type CompletedProjectGalleryFilter = {
  image?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type CompletedProjectFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  location?: InputMaybe<StringFilter>;
  projectType?: InputMaybe<StringFilter>;
  completedYear?: InputMaybe<NumberFilter>;
  durationMonths?: InputMaybe<NumberFilter>;
  gallery?: InputMaybe<CompletedProjectGalleryFilter>;
  videoUrl?: InputMaybe<StringFilter>;
  order?: InputMaybe<NumberFilter>;
};

export type CompletedProjectConnectionEdges = {
  __typename?: 'CompletedProjectConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<CompletedProject>;
};

export type CompletedProjectConnection = Connection & {
  __typename?: 'CompletedProjectConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<CompletedProjectConnectionEdges>>>;
};

export type StatsItems = {
  __typename?: 'StatsItems';
  value: Scalars['String']['output'];
  label: Scalars['String']['output'];
};

export type Stats = Node & Document & {
  __typename?: 'Stats';
  items?: Maybe<Array<Maybe<StatsItems>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StatsItemsFilter = {
  value?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
};

export type StatsFilter = {
  items?: InputMaybe<StatsItemsFilter>;
};

export type StatsConnectionEdges = {
  __typename?: 'StatsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Stats>;
};

export type StatsConnection = Connection & {
  __typename?: 'StatsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<StatsConnectionEdges>>>;
};

export type Testimonial = Node & Document & {
  __typename?: 'Testimonial';
  quote: Scalars['String']['output'];
  name: Scalars['String']['output'];
  location: Scalars['String']['output'];
  service: Scalars['String']['output'];
  order?: Maybe<Scalars['Float']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type TestimonialFilter = {
  quote?: InputMaybe<StringFilter>;
  name?: InputMaybe<StringFilter>;
  location?: InputMaybe<StringFilter>;
  service?: InputMaybe<StringFilter>;
  order?: InputMaybe<NumberFilter>;
};

export type TestimonialConnectionEdges = {
  __typename?: 'TestimonialConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Testimonial>;
};

export type TestimonialConnection = Connection & {
  __typename?: 'TestimonialConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<TestimonialConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateSiteSettings: SiteSettings;
  createSiteSettings: SiteSettings;
  updateFeaturedProperty: FeaturedProperty;
  createFeaturedProperty: FeaturedProperty;
  updateOngoingProject: OngoingProject;
  createOngoingProject: OngoingProject;
  updateCompletedProject: CompletedProject;
  createCompletedProject: CompletedProject;
  updateStats: Stats;
  createStats: Stats;
  updateTestimonial: Testimonial;
  createTestimonial: Testimonial;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateSiteSettingsArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteSettingsMutation;
};


export type MutationCreateSiteSettingsArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteSettingsMutation;
};


export type MutationUpdateFeaturedPropertyArgs = {
  relativePath: Scalars['String']['input'];
  params: FeaturedPropertyMutation;
};


export type MutationCreateFeaturedPropertyArgs = {
  relativePath: Scalars['String']['input'];
  params: FeaturedPropertyMutation;
};


export type MutationUpdateOngoingProjectArgs = {
  relativePath: Scalars['String']['input'];
  params: OngoingProjectMutation;
};


export type MutationCreateOngoingProjectArgs = {
  relativePath: Scalars['String']['input'];
  params: OngoingProjectMutation;
};


export type MutationUpdateCompletedProjectArgs = {
  relativePath: Scalars['String']['input'];
  params: CompletedProjectMutation;
};


export type MutationCreateCompletedProjectArgs = {
  relativePath: Scalars['String']['input'];
  params: CompletedProjectMutation;
};


export type MutationUpdateStatsArgs = {
  relativePath: Scalars['String']['input'];
  params: StatsMutation;
};


export type MutationCreateStatsArgs = {
  relativePath: Scalars['String']['input'];
  params: StatsMutation;
};


export type MutationUpdateTestimonialArgs = {
  relativePath: Scalars['String']['input'];
  params: TestimonialMutation;
};


export type MutationCreateTestimonialArgs = {
  relativePath: Scalars['String']['input'];
  params: TestimonialMutation;
};

export type DocumentUpdateMutation = {
  siteSettings?: InputMaybe<SiteSettingsMutation>;
  featuredProperty?: InputMaybe<FeaturedPropertyMutation>;
  ongoingProject?: InputMaybe<OngoingProjectMutation>;
  completedProject?: InputMaybe<CompletedProjectMutation>;
  stats?: InputMaybe<StatsMutation>;
  testimonial?: InputMaybe<TestimonialMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  siteSettings?: InputMaybe<SiteSettingsMutation>;
  featuredProperty?: InputMaybe<FeaturedPropertyMutation>;
  ongoingProject?: InputMaybe<OngoingProjectMutation>;
  completedProject?: InputMaybe<CompletedProjectMutation>;
  stats?: InputMaybe<StatsMutation>;
  testimonial?: InputMaybe<TestimonialMutation>;
};

export type SiteSettingsComingSoonMutation = {
  headline?: InputMaybe<Scalars['String']['input']>;
  message?: InputMaybe<Scalars['String']['input']>;
  showContact?: InputMaybe<Scalars['Boolean']['input']>;
};

export type SiteSettingsMutation = {
  published?: InputMaybe<Scalars['Boolean']['input']>;
  comingSoon?: InputMaybe<SiteSettingsComingSoonMutation>;
};

export type FeaturedPropertyGalleryMutation = {
  image?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
};

export type FeaturedPropertyMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  tag?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  price?: InputMaybe<Scalars['String']['input']>;
  areaSqft?: InputMaybe<Scalars['Float']['input']>;
  propertyType?: InputMaybe<Scalars['String']['input']>;
  bedrooms?: InputMaybe<Scalars['Float']['input']>;
  bathrooms?: InputMaybe<Scalars['Float']['input']>;
  locality?: InputMaybe<Scalars['String']['input']>;
  possession?: InputMaybe<Scalars['String']['input']>;
  facing?: InputMaybe<Scalars['String']['input']>;
  gallery?: InputMaybe<Array<InputMaybe<FeaturedPropertyGalleryMutation>>>;
  featured?: InputMaybe<Scalars['Boolean']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
};

export type OngoingProjectGalleryMutation = {
  image?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
};

export type OngoingProjectMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  location?: InputMaybe<Scalars['String']['input']>;
  projectType?: InputMaybe<Scalars['String']['input']>;
  percentComplete?: InputMaybe<Scalars['Float']['input']>;
  expectedCompletion?: InputMaybe<Scalars['String']['input']>;
  gallery?: InputMaybe<Array<InputMaybe<OngoingProjectGalleryMutation>>>;
  videoUrl?: InputMaybe<Scalars['String']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
};

export type CompletedProjectGalleryMutation = {
  image?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
};

export type CompletedProjectMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  location?: InputMaybe<Scalars['String']['input']>;
  projectType?: InputMaybe<Scalars['String']['input']>;
  completedYear?: InputMaybe<Scalars['Float']['input']>;
  durationMonths?: InputMaybe<Scalars['Float']['input']>;
  gallery?: InputMaybe<Array<InputMaybe<CompletedProjectGalleryMutation>>>;
  videoUrl?: InputMaybe<Scalars['String']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
};

export type StatsItemsMutation = {
  value?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
};

export type StatsMutation = {
  items?: InputMaybe<Array<InputMaybe<StatsItemsMutation>>>;
};

export type TestimonialMutation = {
  quote?: InputMaybe<Scalars['String']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
  location?: InputMaybe<Scalars['String']['input']>;
  service?: InputMaybe<Scalars['String']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
};

export type BooleanFilter = {
  eq?: boolean | null | undefined;
  exists?: boolean | null | undefined;
};

export type StringFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type SiteSettingsComingSoonFilter = {
  headline?: StringFilter | null | undefined;
  message?: StringFilter | null | undefined;
  showContact?: BooleanFilter | null | undefined;
};

export type SiteSettingsFilter = {
  published?: BooleanFilter | null | undefined;
  comingSoon?: SiteSettingsComingSoonFilter | null | undefined;
};

export type NumberFilter = {
  lt?: number | null | undefined;
  lte?: number | null | undefined;
  gte?: number | null | undefined;
  gt?: number | null | undefined;
  eq?: number | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<number | null | undefined> | null | undefined;
};

export type ImageFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type FeaturedPropertyGalleryFilter = {
  image?: ImageFilter | null | undefined;
  alt?: StringFilter | null | undefined;
};

export type FeaturedPropertyFilter = {
  title?: StringFilter | null | undefined;
  tag?: StringFilter | null | undefined;
  description?: StringFilter | null | undefined;
  price?: StringFilter | null | undefined;
  areaSqft?: NumberFilter | null | undefined;
  propertyType?: StringFilter | null | undefined;
  bedrooms?: NumberFilter | null | undefined;
  bathrooms?: NumberFilter | null | undefined;
  locality?: StringFilter | null | undefined;
  possession?: StringFilter | null | undefined;
  facing?: StringFilter | null | undefined;
  gallery?: FeaturedPropertyGalleryFilter | null | undefined;
  featured?: BooleanFilter | null | undefined;
  order?: NumberFilter | null | undefined;
};

export type OngoingProjectGalleryFilter = {
  image?: ImageFilter | null | undefined;
  alt?: StringFilter | null | undefined;
};

export type OngoingProjectFilter = {
  title?: StringFilter | null | undefined;
  description?: StringFilter | null | undefined;
  location?: StringFilter | null | undefined;
  projectType?: StringFilter | null | undefined;
  percentComplete?: NumberFilter | null | undefined;
  expectedCompletion?: StringFilter | null | undefined;
  gallery?: OngoingProjectGalleryFilter | null | undefined;
  videoUrl?: StringFilter | null | undefined;
  order?: NumberFilter | null | undefined;
};

export type CompletedProjectGalleryFilter = {
  image?: ImageFilter | null | undefined;
  alt?: StringFilter | null | undefined;
};

export type CompletedProjectFilter = {
  title?: StringFilter | null | undefined;
  description?: StringFilter | null | undefined;
  location?: StringFilter | null | undefined;
  projectType?: StringFilter | null | undefined;
  completedYear?: NumberFilter | null | undefined;
  durationMonths?: NumberFilter | null | undefined;
  gallery?: CompletedProjectGalleryFilter | null | undefined;
  videoUrl?: StringFilter | null | undefined;
  order?: NumberFilter | null | undefined;
};

export type StatsItemsFilter = {
  value?: StringFilter | null | undefined;
  label?: StringFilter | null | undefined;
};

export type StatsFilter = {
  items?: StatsItemsFilter | null | undefined;
};

export type TestimonialFilter = {
  quote?: StringFilter | null | undefined;
  name?: StringFilter | null | undefined;
  location?: StringFilter | null | undefined;
  service?: StringFilter | null | undefined;
  order?: NumberFilter | null | undefined;
};

export type SiteSettingsPartsFragment = { __typename: 'SiteSettings', published: boolean | null, comingSoon: { __typename: 'SiteSettingsComingSoon', headline: string, message: string, showContact: boolean | null } | null };

export type FeaturedPropertyPartsFragment = { __typename: 'FeaturedProperty', title: string, tag: string | null, description: string, price: string, areaSqft: number, propertyType: string, bedrooms: number | null, bathrooms: number | null, locality: string, possession: string | null, facing: string | null, featured: boolean | null, order: number | null, gallery: Array<{ __typename: 'FeaturedPropertyGallery', image: string, alt: string }> };

export type OngoingProjectPartsFragment = { __typename: 'OngoingProject', title: string, description: string, location: string, projectType: string, percentComplete: number | null, expectedCompletion: string | null, videoUrl: string | null, order: number | null, gallery: Array<{ __typename: 'OngoingProjectGallery', image: string, alt: string }> };

export type CompletedProjectPartsFragment = { __typename: 'CompletedProject', title: string, description: string, location: string, projectType: string, completedYear: number, durationMonths: number | null, videoUrl: string | null, order: number | null, gallery: Array<{ __typename: 'CompletedProjectGallery', image: string, alt: string }> };

export type StatsPartsFragment = { __typename: 'Stats', items: Array<{ __typename: 'StatsItems', value: string, label: string } | null> | null };

export type TestimonialPartsFragment = { __typename: 'Testimonial', quote: string, name: string, location: string, service: string, order: number | null };

export type SiteSettingsQueryVariables = Exact<{
  relativePath: string;
}>;


export type SiteSettingsQuery = { siteSettings: { __typename: 'SiteSettings', id: string, published: boolean | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, comingSoon: { __typename: 'SiteSettingsComingSoon', headline: string, message: string, showContact: boolean | null } | null } };

export type SiteSettingsConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: SiteSettingsFilter | null | undefined;
}>;


export type SiteSettingsConnectionQuery = { siteSettingsConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'SiteSettings', id: string, published: boolean | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, comingSoon: { __typename: 'SiteSettingsComingSoon', headline: string, message: string, showContact: boolean | null } | null } | null } | null> | null } };

export type FeaturedPropertyQueryVariables = Exact<{
  relativePath: string;
}>;


export type FeaturedPropertyQuery = { featuredProperty: { __typename: 'FeaturedProperty', id: string, title: string, tag: string | null, description: string, price: string, areaSqft: number, propertyType: string, bedrooms: number | null, bathrooms: number | null, locality: string, possession: string | null, facing: string | null, featured: boolean | null, order: number | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, gallery: Array<{ __typename: 'FeaturedPropertyGallery', image: string, alt: string }> } };

export type FeaturedPropertyConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: FeaturedPropertyFilter | null | undefined;
}>;


export type FeaturedPropertyConnectionQuery = { featuredPropertyConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'FeaturedProperty', id: string, title: string, tag: string | null, description: string, price: string, areaSqft: number, propertyType: string, bedrooms: number | null, bathrooms: number | null, locality: string, possession: string | null, facing: string | null, featured: boolean | null, order: number | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, gallery: Array<{ __typename: 'FeaturedPropertyGallery', image: string, alt: string }> } | null } | null> | null } };

export type OngoingProjectQueryVariables = Exact<{
  relativePath: string;
}>;


export type OngoingProjectQuery = { ongoingProject: { __typename: 'OngoingProject', id: string, title: string, description: string, location: string, projectType: string, percentComplete: number | null, expectedCompletion: string | null, videoUrl: string | null, order: number | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, gallery: Array<{ __typename: 'OngoingProjectGallery', image: string, alt: string }> } };

export type OngoingProjectConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: OngoingProjectFilter | null | undefined;
}>;


export type OngoingProjectConnectionQuery = { ongoingProjectConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'OngoingProject', id: string, title: string, description: string, location: string, projectType: string, percentComplete: number | null, expectedCompletion: string | null, videoUrl: string | null, order: number | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, gallery: Array<{ __typename: 'OngoingProjectGallery', image: string, alt: string }> } | null } | null> | null } };

export type CompletedProjectQueryVariables = Exact<{
  relativePath: string;
}>;


export type CompletedProjectQuery = { completedProject: { __typename: 'CompletedProject', id: string, title: string, description: string, location: string, projectType: string, completedYear: number, durationMonths: number | null, videoUrl: string | null, order: number | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, gallery: Array<{ __typename: 'CompletedProjectGallery', image: string, alt: string }> } };

export type CompletedProjectConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: CompletedProjectFilter | null | undefined;
}>;


export type CompletedProjectConnectionQuery = { completedProjectConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'CompletedProject', id: string, title: string, description: string, location: string, projectType: string, completedYear: number, durationMonths: number | null, videoUrl: string | null, order: number | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, gallery: Array<{ __typename: 'CompletedProjectGallery', image: string, alt: string }> } | null } | null> | null } };

export type StatsQueryVariables = Exact<{
  relativePath: string;
}>;


export type StatsQuery = { stats: { __typename: 'Stats', id: string, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items: Array<{ __typename: 'StatsItems', value: string, label: string } | null> | null } };

export type StatsConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: StatsFilter | null | undefined;
}>;


export type StatsConnectionQuery = { statsConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Stats', id: string, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items: Array<{ __typename: 'StatsItems', value: string, label: string } | null> | null } | null } | null> | null } };

export type TestimonialQueryVariables = Exact<{
  relativePath: string;
}>;


export type TestimonialQuery = { testimonial: { __typename: 'Testimonial', id: string, quote: string, name: string, location: string, service: string, order: number | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type TestimonialConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: TestimonialFilter | null | undefined;
}>;


export type TestimonialConnectionQuery = { testimonialConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Testimonial', id: string, quote: string, name: string, location: string, service: string, order: number | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const SiteSettingsPartsFragmentDoc = gql`
    fragment SiteSettingsParts on SiteSettings {
  __typename
  published
  comingSoon {
    __typename
    headline
    message
    showContact
  }
}
    `;
export const FeaturedPropertyPartsFragmentDoc = gql`
    fragment FeaturedPropertyParts on FeaturedProperty {
  __typename
  title
  tag
  description
  price
  areaSqft
  propertyType
  bedrooms
  bathrooms
  locality
  possession
  facing
  gallery {
    __typename
    image
    alt
  }
  featured
  order
}
    `;
export const OngoingProjectPartsFragmentDoc = gql`
    fragment OngoingProjectParts on OngoingProject {
  __typename
  title
  description
  location
  projectType
  percentComplete
  expectedCompletion
  gallery {
    __typename
    image
    alt
  }
  videoUrl
  order
}
    `;
export const CompletedProjectPartsFragmentDoc = gql`
    fragment CompletedProjectParts on CompletedProject {
  __typename
  title
  description
  location
  projectType
  completedYear
  durationMonths
  gallery {
    __typename
    image
    alt
  }
  videoUrl
  order
}
    `;
export const StatsPartsFragmentDoc = gql`
    fragment StatsParts on Stats {
  __typename
  items {
    __typename
    value
    label
  }
}
    `;
export const TestimonialPartsFragmentDoc = gql`
    fragment TestimonialParts on Testimonial {
  __typename
  quote
  name
  location
  service
  order
}
    `;
export const SiteSettingsDocument = gql`
    query siteSettings($relativePath: String!) {
  siteSettings(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SiteSettingsParts
  }
}
    ${SiteSettingsPartsFragmentDoc}`;
export const SiteSettingsConnectionDocument = gql`
    query siteSettingsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SiteSettingsFilter) {
  siteSettingsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SiteSettingsParts
      }
    }
  }
}
    ${SiteSettingsPartsFragmentDoc}`;
export const FeaturedPropertyDocument = gql`
    query featuredProperty($relativePath: String!) {
  featuredProperty(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...FeaturedPropertyParts
  }
}
    ${FeaturedPropertyPartsFragmentDoc}`;
export const FeaturedPropertyConnectionDocument = gql`
    query featuredPropertyConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: FeaturedPropertyFilter) {
  featuredPropertyConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...FeaturedPropertyParts
      }
    }
  }
}
    ${FeaturedPropertyPartsFragmentDoc}`;
export const OngoingProjectDocument = gql`
    query ongoingProject($relativePath: String!) {
  ongoingProject(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...OngoingProjectParts
  }
}
    ${OngoingProjectPartsFragmentDoc}`;
export const OngoingProjectConnectionDocument = gql`
    query ongoingProjectConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: OngoingProjectFilter) {
  ongoingProjectConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...OngoingProjectParts
      }
    }
  }
}
    ${OngoingProjectPartsFragmentDoc}`;
export const CompletedProjectDocument = gql`
    query completedProject($relativePath: String!) {
  completedProject(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...CompletedProjectParts
  }
}
    ${CompletedProjectPartsFragmentDoc}`;
export const CompletedProjectConnectionDocument = gql`
    query completedProjectConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: CompletedProjectFilter) {
  completedProjectConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...CompletedProjectParts
      }
    }
  }
}
    ${CompletedProjectPartsFragmentDoc}`;
export const StatsDocument = gql`
    query stats($relativePath: String!) {
  stats(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...StatsParts
  }
}
    ${StatsPartsFragmentDoc}`;
export const StatsConnectionDocument = gql`
    query statsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: StatsFilter) {
  statsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...StatsParts
      }
    }
  }
}
    ${StatsPartsFragmentDoc}`;
export const TestimonialDocument = gql`
    query testimonial($relativePath: String!) {
  testimonial(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...TestimonialParts
  }
}
    ${TestimonialPartsFragmentDoc}`;
export const TestimonialConnectionDocument = gql`
    query testimonialConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: TestimonialFilter) {
  testimonialConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...TestimonialParts
      }
    }
  }
}
    ${TestimonialPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      siteSettings(variables: SiteSettingsQueryVariables, options?: C): Promise<{data: SiteSettingsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteSettingsQueryVariables, query: string}> {
        return requester<{data: SiteSettingsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteSettingsQueryVariables, query: string}, SiteSettingsQueryVariables>(SiteSettingsDocument, variables, options);
      },
    siteSettingsConnection(variables?: SiteSettingsConnectionQueryVariables, options?: C): Promise<{data: SiteSettingsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteSettingsConnectionQueryVariables, query: string}> {
        return requester<{data: SiteSettingsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteSettingsConnectionQueryVariables, query: string}, SiteSettingsConnectionQueryVariables>(SiteSettingsConnectionDocument, variables, options);
      },
    featuredProperty(variables: FeaturedPropertyQueryVariables, options?: C): Promise<{data: FeaturedPropertyQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FeaturedPropertyQueryVariables, query: string}> {
        return requester<{data: FeaturedPropertyQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FeaturedPropertyQueryVariables, query: string}, FeaturedPropertyQueryVariables>(FeaturedPropertyDocument, variables, options);
      },
    featuredPropertyConnection(variables?: FeaturedPropertyConnectionQueryVariables, options?: C): Promise<{data: FeaturedPropertyConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FeaturedPropertyConnectionQueryVariables, query: string}> {
        return requester<{data: FeaturedPropertyConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FeaturedPropertyConnectionQueryVariables, query: string}, FeaturedPropertyConnectionQueryVariables>(FeaturedPropertyConnectionDocument, variables, options);
      },
    ongoingProject(variables: OngoingProjectQueryVariables, options?: C): Promise<{data: OngoingProjectQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: OngoingProjectQueryVariables, query: string}> {
        return requester<{data: OngoingProjectQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: OngoingProjectQueryVariables, query: string}, OngoingProjectQueryVariables>(OngoingProjectDocument, variables, options);
      },
    ongoingProjectConnection(variables?: OngoingProjectConnectionQueryVariables, options?: C): Promise<{data: OngoingProjectConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: OngoingProjectConnectionQueryVariables, query: string}> {
        return requester<{data: OngoingProjectConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: OngoingProjectConnectionQueryVariables, query: string}, OngoingProjectConnectionQueryVariables>(OngoingProjectConnectionDocument, variables, options);
      },
    completedProject(variables: CompletedProjectQueryVariables, options?: C): Promise<{data: CompletedProjectQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CompletedProjectQueryVariables, query: string}> {
        return requester<{data: CompletedProjectQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CompletedProjectQueryVariables, query: string}, CompletedProjectQueryVariables>(CompletedProjectDocument, variables, options);
      },
    completedProjectConnection(variables?: CompletedProjectConnectionQueryVariables, options?: C): Promise<{data: CompletedProjectConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CompletedProjectConnectionQueryVariables, query: string}> {
        return requester<{data: CompletedProjectConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CompletedProjectConnectionQueryVariables, query: string}, CompletedProjectConnectionQueryVariables>(CompletedProjectConnectionDocument, variables, options);
      },
    stats(variables: StatsQueryVariables, options?: C): Promise<{data: StatsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: StatsQueryVariables, query: string}> {
        return requester<{data: StatsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: StatsQueryVariables, query: string}, StatsQueryVariables>(StatsDocument, variables, options);
      },
    statsConnection(variables?: StatsConnectionQueryVariables, options?: C): Promise<{data: StatsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: StatsConnectionQueryVariables, query: string}> {
        return requester<{data: StatsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: StatsConnectionQueryVariables, query: string}, StatsConnectionQueryVariables>(StatsConnectionDocument, variables, options);
      },
    testimonial(variables: TestimonialQueryVariables, options?: C): Promise<{data: TestimonialQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestimonialQueryVariables, query: string}> {
        return requester<{data: TestimonialQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestimonialQueryVariables, query: string}, TestimonialQueryVariables>(TestimonialDocument, variables, options);
      },
    testimonialConnection(variables?: TestimonialConnectionQueryVariables, options?: C): Promise<{data: TestimonialConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestimonialConnectionQueryVariables, query: string}> {
        return requester<{data: TestimonialConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestimonialConnectionQueryVariables, query: string}, TestimonialConnectionQueryVariables>(TestimonialConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

export type { Exact };

  